# Generated by Django 6.1.1 on 2026-09-09 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_art', models.CharField(max_length=150, null=True)),
                ('name_of_artist', models.CharField(max_length=150, null=True)),
                ('price_of_art', models.IntegerField(max_length=20)),
                ('desc_of_art', models.TextField()),
                ('image_of_art', models.ImageField(upload_to='')),
            ],
        ),
    ]
