# Generated by Django 6.1.1 on 2026-09-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_art', models.CharField(max_length=100)),
                ('title_art', models.CharField(max_length=200)),
                ('description_art', models.TextField()),
                ('image_art', models.ImageField(upload_to='')),
            ],
        ),
    ]
