# Generated by Django 6.1.1 on 2026-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='title_art',
        ),
        migrations.AddField(
            model_name='art',
            name='name_artist',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='name_art',
            field=models.CharField(max_length=200),
        ),
    ]
