# Generated by Django 6.1.1 on 2026-09-09 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=150, null=True)),
                ('course_desc', models.TextField()),
                ('course_tutor_name', models.CharField(max_length=150, null=True)),
                ('course_price', models.IntegerField(max_length=10)),
                ('course_video', models.FileField(null=True, upload_to='videos_uploaded/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv', 'wmv', 'avi', 'mov'])])),
            ],
        ),
    ]
