# Generated by Django 6.1.1 on 2026-09-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.IntegerField(),
        ),
    ]
